/*********************************************************************************** 
This is automatically generated by vue create command
We should probably never have to change anything in here

Vue uses this to inject our Vue components into theindex.html
***********************************************************************************/

import Vue from 'vue'         // Give me access to the Vue stuff
import App from './App.vue'   // Give me access to the App.vue component

Vue.config.productionTip = false    // Disable hints about Vue for the App
                                    // no longer needed as it is not the default

new Vue({                     // Instantiate a Vue application object
  render: h => h(App),        // Render tells Vue what the main component is called - must match name of an import
}).$mount('#app')             // $mount - tells Vue where in the index.html the Vue component should be added
                              //        #app - the element with id='app' will have the Vue components added to it
